baseURL = "/"
languageCode = "en-us"
title = "Hugo Sandbox"
relativeurls = false

[permalinks]
  posts = "/:year/:month/:title/"

[sitemap]
  filename = "sitemap.xml"

[build]
  writeStats = true

[minify]
  minifyOutput = true