backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# when using the default proxy server port
local_backend: true

media_folder: "/content/media" # Media files will be stored in the repo under /content/media
public_folder: "/media" # The src attribute for uploaded media will begin with /media

collections:
  - name: "page" # Used in routes, ie.: /admin/collections/:slug/edit
    create: true # Allow users to create new documents in this collection
    folder: "content" # The path to the folder where the documents are stored
    label: "Pages" # Used in the UI, ie.: "New Post"
    label_singular: "Page"
    fields: # The fields each document in this collection have
      - label: "Title"
        name: "title"
        widget: "string"
        hint: "This is your page title."
      - label: "Link Title"
        name: "linktitle"
        widget: "string"
        required: false
        hint: "Overwrite the title when linked to this page. Such as main or footer navigation menus."
      - label: "Summary"
        name: "summary"
        widget: "text"
        required: false
        hint: "Provide a snippet for SEO & social meta tags information. If nothing is provided it will use the first 70 words of the content."
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
        hint: "Maximum filesize of 5MB."
        media_library:
          config:
            max_file_size: 5000000 # in bytes, only for default media library
      - label: "Call to Action"
        name: "cta"
        widget: "relation"
        collection: "page"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        required: false
        hint: "Select a page for menu prominence"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "settings" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Settings" # Used in the UI, ie.: "New Post"
    editor:
      preview: false
    files:
      - name: "main-navigation"
        file: "content/settings/main-navigation.md"
        label: "Main Navigation"
        fields:
          - label: "Menu"
            name: "menu"
            widget: "list"
            default: []
            label_singular: "Menu"
            summary: "linktitle"
            types:
              - label: 'Page'
                name: 'page'
                widget: object
                summary: '{{ fields.linktitle }}'
                fields:
                  - label: "Page"
                    name: "page"
                    widget: "relation"
                    collection: "page"
                    search_fields: ["title"]
                    value_field: "{{slug}}"
                    display_fields: ["title"]
              - label: 'Custom Link'
                name: 'custom'
                widget: object
                summary: '{{ fields.linktitle }}'
                fields:
                  - { label: "Title", name: "linktitle", widget: "string" }
                  - { label: "Url", name: "url", widget: "string" }
                  - { label: "Open in New Window", name: "external", widget: "boolean", default: true }
          - label: "Call to Action"
            name: "cta"
            widget: "relation"
            collection: "page"
            search_fields: ["title"]
            value_field: "{{slug}}"
            display_fields: ["title"]
            required: false
            hint: "Select a page for menu prominence"
      - name: "identity"
        file: "content/settings/identity.md"
        label: "Identity"
        fields:
          - label: "Favicon"
            name: "favicon"
            widget: "image"
            required: false
            hint: "A favicon is a small square icon displayed in a browser tab for easy identification. Image should be a transparent square png that's at least 270x270."
          - label: "Logo"
            name: "logo"
            widget: "image"
            required: false
            hint: "Image should be a landscape"
      - name: "socials"
        file: "content/settings/socials.md"
        label: "Social Media"
        fields:
          - label: "Facebook"
            name: "facebook"
            widget: "string"
            required: false
            hint: "Full link to your Facebook page"
          - label: "Twitter"
            name: "twitter"
            widget: "string"
            required: false
            hint: "Full link to your Twitter profile"
          - label: "LinkedIn"
            name: "linkedin"
            widget: "string"
            required: false
            hint: "Full link to your LinkedIn page"
          - label: "Instagram"
            name: "instagram"
            widget: "string"
            required: false
            hint: "Full link to your Instagram profile"
          - label: "YouTube"
            name: "youtube"
            widget: "string"
            required: false
            hint: "Full link to your YouTube channel"
          - label: "Vimeo"
            name: "vimeo"
            widget: "string"
            required: false
            hint: "Full link to your Vimeo page"
          - label: "Slack"
            name: "slack"
            widget: "string"
            required: false
            hint: "Full link to your Slack group, for public access"
        